### ISSUE TITLE
FaradayMiddleware::Gzip has a problem with `deflate` encoding compatibility

### ISSUE THREAD

**Issue by knu** [lostisland/faraday_middleware#119]
The `deflate` encoding seems to refer to one of the following formats depending on the implementation:

- "DEFLATE": a zlib stream containing a raw deflate stream (This is what RFC defines)
- "deflate": a raw deflate stream

cf. https://en.wikipedia.org/wiki/HTTP_compression#Problems_preventing_the_use_of_HTTP_compression

So, there's a compatibility problem here.  Microsoft servers and [Rack::Deflate](https://github.com/rack/rack/blob/master/lib/rack/deflater.rb#L107-L108
) adopt the latter, while there are servers that adopt the former including Apache's mod_deflate.
Major browsers (i.e. clients) support both, so this problem may be rather unknown.

FaradayMiddleware::Gzip currently is only aware of DEFLATE, so if it receives a raw deflate stream it will fail with "incorrect header check" (Zlib::DataError).

I think the middleware could implement a fallback as follows, as well as dropping `deflate` from the default `Accept-Encoding` request header value for safety.

```ruby
    def inflate(body)
      # Inflate as a DEFLATE (RFC 1950+RFC 1951) stream
      Zlib::Inflate.inflate(body)
    rescue Zlib::DataError
      begin
        # Fall back to inflating as a "raw" deflate stream which
        # Microsoft servers return
        inflate = Zlib::Inflate.new(-Zlib::MAX_WBITS)
        inflate.inflate(body)
      ensure
        inflate.close
      end
    end
```

What do you guys think?  I'd be happy to make a PR, but just wanted to make sure to share the problem before that.

**Comment by knu** [comment]
An example URL of a deflate'd page that the Gzip middleware fails to handle is given in the above issue.
`Zlib::Inflate.inflate` cannot decode a raw deflate stream.
```
% curl -L -H 'Accept-Encoding: deflate' 'http://jobboerse.arbeitsagentur.de/vamJB/stellenangeboteFinden.html?execution=e1s1' | ruby -rzlib -e 'Zlib::Inflate.inflate($<.read)'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   423    0   423    0     0    623      0 --:--:-- --:--:-- --:--:--   622
100   451    0   451    0     0    463      0 --:--:-- --:--:-- --:--:--   463
100 11292    0 11292    0     0   8612      0 --:--:--  0:00:01 --:--:-- 2661k
-e:1:in `inflate': incorrect header check (Zlib::DataError)
        from -e:1:in `<main>'
```

You can confirm Firefox and Chrome can successfully decode the response content with `Content-Encoding: deflate` using the "Network" tab of their developer tools.

/cc @romanbsd

**Comment by knu** [comment]
Here's a repro.
```
% ruby -rfaraday -rfaraday_middleware -e 'Faraday.new {|b| b.use FaradayMiddleware::FollowRedirects; b.use :gzip; b.adapter Faraday.default_adapter }.get("http://jobboerse.arbeitsagentur.de/vamJB/stellenangeboteFinden.html?execution=e1s1")'
/..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/gzip.rb:51:in `inflate': incorrect header check (Zlib::DataError)
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/gzip.rb:51:in `inflate'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/gzip.rb:35:in `reset_body'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/gzip.rb:29:in `block in call'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/gzip.rb:24:in `call'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection
'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:82:in `block in perform_with_re
direction'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection
'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:82:in `block in perform_with_re
direction'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection
'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /..prefix../lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
        from -e:1:in `<main>'
```

**Comment by knu** [comment]
Please review the PR above.
