### ISSUE TITLE
JSON response middleware seems to break URL encoding / form encoding for POST requests

### ISSUE THREAD

**Issue by danarnold** [lostisland/faraday_middleware#176]
When using the JSON response middleware, form data in post requests is not properly encoded.

A working example, without the JSON middleware:

```ruby
 (main)> connection = Faraday.new(url: server_url)
#<Faraday::Connection:0x00007fdfdb924920 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.12.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00007fdfdb9245d8 @handlers=[Faraday::Request::UrlEncoded, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTP http://localhost:4567/>, @proxy=nil>
 (main)> connection.post('/', {a: 'b'})
#<Faraday::Response:0x00007fdfdc1aa590 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="thanks!" @url=#<URI::HTTP http://localhost:4567/> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.12.2", "Content-Type"=>"application/x-www-form-urlencoded"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x00007fdfdc1aa590 ...> @response_headers={"content-type"=>"text/html;charset=utf-8", "content-length"=>"7", "x-xss-protection"=>"1; mode=block", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "server"=>"WEBrick/1.3.1 (Ruby/2.4.1/2017-03-22)", "date"=>"Tue, 01 May 2018 22:33:02 GMT", "connection"=>"close"} @status=200 @reason_phrase="OK">>
```

Adding in the JSON middleware, we get an error in Faraday::Middleware, in the response middleware files; however, the request has not hit the server and has not even been made.

```ruby
 (main)> connection = Faraday.new(url: server_url) do |conn|
 (main)*   conn.response :json, :content_type => /\bjson$/
 (main)* end
#<Faraday::Connection:0x00007fdfd1545b60 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.12.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00007fdfd15457f0 @handlers=[FaradayMiddleware::ParseJson]>, @url_prefix=#<URI::HTTP http://localhost:4567/>, @proxy=nil>
 (main)> connection.post('/', {a: 'b'})
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/dan/.rvm/gems/ruby-2.3.7@project/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:59:in `response_type'
```

Adding in `url_encoded` request middleware does not fix this:

```ruby
 (main)> connection = Faraday.new(url: server_url) do |conn|
 (main)*   conn.response :json, :content_type => /\bjson$/
 (main)*   conn.request :url_encoded
 (main)* end
#<Faraday::Connection:0x00007fdfdbab4dd0 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.12.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00007fdfdbab4a60 @handlers=[FaradayMiddleware::ParseJson, Faraday::Request::UrlEncoded]>, @url_prefix=#<URI::HTTP http://localhost:4567/>, @proxy=nil>
 (main)> connection.post('/', {a: 'b'})
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/dan/.rvm/gems/ruby-2.3.7@project/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:59:in `response_type'
```

The only way to get this to work is by manually specifying net_http as the adapter via `Faraday.default_adapter` and manually writing out the form data:

```ruby
 (main)> connection = Faraday.new(url: server_url) do |conn|
 (main)*   conn.response :json, :content_type => /\bjson$/
      conn.adapter Faraday.default_adapter
 (main)*   conn.adapter Faraday.default_adapter
 (main)* end
#<Faraday::Connection:0x00007fdfd787d480 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.12.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00007fdfd787d0c0 @handlers=[FaradayMiddleware::ParseJson, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTP http://localhost:4567/>, @proxy=nil>
 (main)> connection.post('/v') { |conn| conn.body = "a=b" }
#<Faraday::Response:0x00007fdfd7a19320 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="thanks!" @url=#<URI::HTTP http://localhost:4567/v> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.12.2"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x00007fdfd7a19320 ...> @response_headers={"content-type"=>"text/html;charset=utf-8", "content-length"=>"7", "x-xss-protection"=>"1; mode=block", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "server"=>"WEBrick/1.3.1 (Ruby/2.4.1/2017-03-22)", "date"=>"Tue, 01 May 2018 22:39:51 GMT", "connection"=>"close"} @status=200 @reason_phrase="OK">>
```

With the same `connection` initialized, here I try the simple syntax again, which is still broken with the adapter manually specified, just with a different error:

```ruby
 (main)> connection.post('/a', {a: 'b'})
NoMethodError: undefined method `bytesize' for {:a=>"b"}:Hash
from /Users/dan/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/net/http/generic_request.rb:183:in `send_request_with_body'
```

I hope this information is helpful in resolving this issue. I am using an older version of Faraday::Middleware here, but I tried it with 0.12.2 and I get the same errors.

**Comment by iMacTia** [comment]
Hi @danarnold, the main issue I can see is that when you add the json response middleware, you are loosing the default stack.
This is a very common issue and we're working towards solving it in the next major version of Faraday.

In short, you simply need to re-specify the default stack when you want to add custom middlewares:

```ruby
connection = Faraday.new(url: server_url) do |conn|
  conn.request :url_encoded # Default stack request encoding
  conn.response :json, :content_type => /\bjson$/ # Custom middleware
  conn.adapter Faraday.default_adapter # Default stack adapter
end
```

Please let me know if the above works

**Comment by danarnold** [comment]
Yes, that does indeed fix it. Thank you for the assistance, and I look forward to the next version of Faraday.
